name: static deploy app
on:
  push:
    branches:
      - master
jobs:
    build:
        name: deploy Tetris
        runs-on: ubuntu-latest
        steps:
        - name: deploy over ssh
          uses:  appleboy/ssh-action@v0.1.10
          with:            
            host: ${{ secrets.HOST  }}
            username: ${{ secrets.USRNAME  }}
            key: ${{ secrets.PASSWORD  }}
            
            script: whoami
            
