name: static deploy app
on:
  push:
    branches:
      - master
jobs:
    build:
        name: deploy Tetris
        runs-on: ubuntu-latest
        steps:
        - name: deploy over ssh
          uses:  appleboy/ssh-action@v0.1.10
          with:            
            host: ${{ secrets.HOST  }}
            username: ${{ secrets.USERNAME  }}
            key: ${{ secrets.PASSWORD  }}
            
            script: |
              cd /var/www/html/HTML5-Tetris
              git config --global --add safe.directory /var/www/html/HTML5-Tetris

              sudo git pull
              sudo systemctl restart nginx
            
